name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js (for building on GitHub)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Frontend exactly on GitHub Servers
        env:
          VITE_API_URL: "/api"
        run: |
          cd client
          npm install
          npm run build
          
      - name: Pull Latest Backend Code on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/application/trackly
            git restore .
            git pull origin main

      - name: Copy Built Frontend directly to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # Copy the entire dist folder we just built
          source: "client/dist"
          # It puts 'client/dist' inside the target folder
          target: "/root/application/trackly"

      - name: Install Backend Deps & Restart Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Sync the fresh code (frontend and backend) to Nginx's live directory
            rsync -avz /root/application/trackly/ /var/www/trackly/
            
            cd /var/www/trackly/server
            npm install
            pm2 restart all
